version: '3.5'

services:
  postgres:
    container_name: postgres_db
    image: postgres:16.0
    environment:
      - POSTGRES_USER=shaturko_maksim
      - POSTGRES_PASSWORD=02042010
      - POSTGRES_DB=users_db
    ports:
      - "5434:5432"